name: Code Quality

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/workflows/code-quality.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'

jobs:
  format-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Check formatting
        run: bun run check-formatting

      - name: Check linting
        run: bun run lint
