name: Run Tests

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '/.github/workflows/test.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Cypress
        run: bun add cypress --dev && bun run cypress install

      - name: Run tests
        run: bun run test:e2e

      - name: Generate coverage badge
        run: |
          COVERAGE=$(cat coverage/coverage-summary.json | jq -r '.total.lines.pct')
          echo "COVERAGE=$COVERAGE" >> $GITHUB_ENV
          
      - name: Create coverage badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: c98e952b992d7ee35c453fddfd7e2f5e
          filename: macgarden-coverage.json
          label: coverage
          message: ${{ env.COVERAGE }}%
          color: ${{ job.status == 'success' && env.COVERAGE >= 80 ? 'success' : 'failure' }}